/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostLoginRouteImport } from './routes/post-login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ServicesWebsitesRouteImport } from './routes/services/websites'
import { Route as ServicesWebAppsRouteImport } from './routes/services/web-apps'
import { Route as ServicesVoiceAiRouteImport } from './routes/services/voice-ai'
import { Route as ServicesChatAiRouteImport } from './routes/services/chat-ai'
import { Route as ServicesAiAutomationsRouteImport } from './routes/services/ai-automations'
import { Route as ServicesAiAssistantsRouteImport } from './routes/services/ai-assistants'
import { Route as PortalProposalsRouteImport } from './routes/portal/proposals'
import { Route as PortalProjectsRouteImport } from './routes/portal/projects'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as DashboardTimeTrackingRouteImport } from './routes/dashboard/time-tracking'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard/submissions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProposalsRouteImport } from './routes/dashboard/proposals'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as PortalProposalsIdRouteImport } from './routes/portal/proposals.$id'
import { Route as DashboardProposalsNewRouteImport } from './routes/dashboard/proposals.new'
import { Route as DashboardProposalsIdRouteImport } from './routes/dashboard/proposals.$id'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard/projects.$id'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRoute = PostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/services/websites',
  path: '/services/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebAppsRoute = ServicesWebAppsRouteImport.update({
  id: '/services/web-apps',
  path: '/services/web-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVoiceAiRoute = ServicesVoiceAiRouteImport.update({
  id: '/services/voice-ai',
  path: '/services/voice-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesChatAiRoute = ServicesChatAiRouteImport.update({
  id: '/services/chat-ai',
  path: '/services/chat-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAutomationsRoute = ServicesAiAutomationsRouteImport.update({
  id: '/services/ai-automations',
  path: '/services/ai-automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAssistantsRoute = ServicesAiAssistantsRouteImport.update({
  id: '/services/ai-assistants',
  path: '/services/ai-assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProposalsRoute = PortalProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTimeTrackingRoute = DashboardTimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProposalsRoute = DashboardProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalProposalsIdRoute = PortalProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalProposalsRoute,
} as any)
const DashboardProposalsNewRoute = DashboardProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProposalsRoute,
} as any)
const DashboardProposalsIdRoute = DashboardProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProposalsRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/proposals': typeof DashboardProposalsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/time-tracking': typeof DashboardTimeTrackingRoute
  '/pay/$id': typeof PayIdRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/proposals': typeof PortalProposalsRouteWithChildren
  '/services/ai-assistants': typeof ServicesAiAssistantsRoute
  '/services/ai-automations': typeof ServicesAiAutomationsRoute
  '/services/chat-ai': typeof ServicesChatAiRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/web-apps': typeof ServicesWebAppsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/proposals/$id': typeof DashboardProposalsIdRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/proposals': typeof DashboardProposalsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/time-tracking': typeof DashboardTimeTrackingRoute
  '/pay/$id': typeof PayIdRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/proposals': typeof PortalProposalsRouteWithChildren
  '/services/ai-assistants': typeof ServicesAiAssistantsRoute
  '/services/ai-automations': typeof ServicesAiAutomationsRoute
  '/services/chat-ai': typeof ServicesChatAiRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/web-apps': typeof ServicesWebAppsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/proposals/$id': typeof DashboardProposalsIdRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/proposals': typeof DashboardProposalsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/time-tracking': typeof DashboardTimeTrackingRoute
  '/pay/$id': typeof PayIdRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/proposals': typeof PortalProposalsRouteWithChildren
  '/services/ai-assistants': typeof ServicesAiAssistantsRoute
  '/services/ai-automations': typeof ServicesAiAutomationsRoute
  '/services/chat-ai': typeof ServicesChatAiRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/web-apps': typeof ServicesWebAppsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/proposals/$id': typeof DashboardProposalsIdRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/dashboard'
    | '/portal'
    | '/post-login'
    | '/privacy'
    | '/dashboard/clients'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/time-tracking'
    | '/pay/$id'
    | '/portal/projects'
    | '/portal/proposals'
    | '/services/ai-assistants'
    | '/services/ai-automations'
    | '/services/chat-ai'
    | '/services/voice-ai'
    | '/services/web-apps'
    | '/services/websites'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/projects/$id'
    | '/dashboard/proposals/$id'
    | '/dashboard/proposals/new'
    | '/portal/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/post-login'
    | '/privacy'
    | '/dashboard/clients'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/time-tracking'
    | '/pay/$id'
    | '/portal/projects'
    | '/portal/proposals'
    | '/services/ai-assistants'
    | '/services/ai-automations'
    | '/services/chat-ai'
    | '/services/voice-ai'
    | '/services/web-apps'
    | '/services/websites'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard'
    | '/portal'
    | '/dashboard/projects/$id'
    | '/dashboard/proposals/$id'
    | '/dashboard/proposals/new'
    | '/portal/proposals/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/dashboard'
    | '/portal'
    | '/post-login'
    | '/privacy'
    | '/dashboard/clients'
    | '/dashboard/projects'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/time-tracking'
    | '/pay/$id'
    | '/portal/projects'
    | '/portal/proposals'
    | '/services/ai-assistants'
    | '/services/ai-automations'
    | '/services/chat-ai'
    | '/services/voice-ai'
    | '/services/web-apps'
    | '/services/websites'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/projects/$id'
    | '/dashboard/proposals/$id'
    | '/dashboard/proposals/new'
    | '/portal/proposals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PostLoginRoute: typeof PostLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PayIdRoute: typeof PayIdRoute
  ServicesAiAssistantsRoute: typeof ServicesAiAssistantsRoute
  ServicesAiAutomationsRoute: typeof ServicesAiAutomationsRoute
  ServicesChatAiRoute: typeof ServicesChatAiRoute
  ServicesVoiceAiRoute: typeof ServicesVoiceAiRoute
  ServicesWebAppsRoute: typeof ServicesWebAppsRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login': {
      id: '/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof PostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/services/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-apps': {
      id: '/services/web-apps'
      path: '/services/web-apps'
      fullPath: '/services/web-apps'
      preLoaderRoute: typeof ServicesWebAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/voice-ai': {
      id: '/services/voice-ai'
      path: '/services/voice-ai'
      fullPath: '/services/voice-ai'
      preLoaderRoute: typeof ServicesVoiceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chat-ai': {
      id: '/services/chat-ai'
      path: '/services/chat-ai'
      fullPath: '/services/chat-ai'
      preLoaderRoute: typeof ServicesChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-automations': {
      id: '/services/ai-automations'
      path: '/services/ai-automations'
      fullPath: '/services/ai-automations'
      preLoaderRoute: typeof ServicesAiAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-assistants': {
      id: '/services/ai-assistants'
      path: '/services/ai-assistants'
      fullPath: '/services/ai-assistants'
      preLoaderRoute: typeof ServicesAiAssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/proposals': {
      id: '/portal/proposals'
      path: '/proposals'
      fullPath: '/portal/proposals'
      preLoaderRoute: typeof PortalProposalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/time-tracking': {
      id: '/dashboard/time-tracking'
      path: '/time-tracking'
      fullPath: '/dashboard/time-tracking'
      preLoaderRoute: typeof DashboardTimeTrackingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/proposals': {
      id: '/dashboard/proposals'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/proposals/$id': {
      id: '/portal/proposals/$id'
      path: '/$id'
      fullPath: '/portal/proposals/$id'
      preLoaderRoute: typeof PortalProposalsIdRouteImport
      parentRoute: typeof PortalProposalsRoute
    }
    '/dashboard/proposals/new': {
      id: '/dashboard/proposals/new'
      path: '/new'
      fullPath: '/dashboard/proposals/new'
      preLoaderRoute: typeof DashboardProposalsNewRouteImport
      parentRoute: typeof DashboardProposalsRoute
    }
    '/dashboard/proposals/$id': {
      id: '/dashboard/proposals/$id'
      path: '/$id'
      fullPath: '/dashboard/proposals/$id'
      preLoaderRoute: typeof DashboardProposalsIdRouteImport
      parentRoute: typeof DashboardProposalsRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
  }
}

interface DashboardProjectsRouteChildren {
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardProposalsRouteChildren {
  DashboardProposalsIdRoute: typeof DashboardProposalsIdRoute
  DashboardProposalsNewRoute: typeof DashboardProposalsNewRoute
}

const DashboardProposalsRouteChildren: DashboardProposalsRouteChildren = {
  DashboardProposalsIdRoute: DashboardProposalsIdRoute,
  DashboardProposalsNewRoute: DashboardProposalsNewRoute,
}

const DashboardProposalsRouteWithChildren =
  DashboardProposalsRoute._addFileChildren(DashboardProposalsRouteChildren)

interface DashboardRouteChildren {
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardProposalsRoute: typeof DashboardProposalsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardTimeTrackingRoute: typeof DashboardTimeTrackingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardProposalsRoute: DashboardProposalsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardTimeTrackingRoute: DashboardTimeTrackingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalProposalsRouteChildren {
  PortalProposalsIdRoute: typeof PortalProposalsIdRoute
}

const PortalProposalsRouteChildren: PortalProposalsRouteChildren = {
  PortalProposalsIdRoute: PortalProposalsIdRoute,
}

const PortalProposalsRouteWithChildren = PortalProposalsRoute._addFileChildren(
  PortalProposalsRouteChildren,
)

interface PortalRouteChildren {
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalProposalsRoute: typeof PortalProposalsRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalProjectsRoute: PortalProjectsRoute,
  PortalProposalsRoute: PortalProposalsRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PostLoginRoute: PostLoginRoute,
  PrivacyRoute: PrivacyRoute,
  PayIdRoute: PayIdRoute,
  ServicesAiAssistantsRoute: ServicesAiAssistantsRoute,
  ServicesAiAutomationsRoute: ServicesAiAutomationsRoute,
  ServicesChatAiRoute: ServicesChatAiRoute,
  ServicesVoiceAiRoute: ServicesVoiceAiRoute,
  ServicesWebAppsRoute: ServicesWebAppsRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
